name: Mypy Check

on: [push, pull_request]

jobs:
  mypy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: 3.7

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        # pip install mypy
    # - name: Run mypy
    #   run: mypy custom/screen/sh1106_i2c.py --config-file .github/mypy.ini
      
    - name: Set executable permission for mpy-cross
      run: chmod +x .build/mpy-cross
      
    - name: Run mpy
      run: |
        mkdir -p build
        find . -name '*.py' ! -name 'code.py' ! -name 'boot.py' -exec sh -c '
          for file; do
            mkdir -p "build/$(dirname "$file")"
            .build/mpy-cross -o "build/${file%.py}.mpy" "$file"
          done
        ' sh {} +

    - name: Build depoly zip
      run: |
        cp -r lib build/
        cp -r .fseventsd build/
        cp .metadata_never_index build/
        cp .Trash-1000 build/
        cp .Trashes build/
        cp settings.toml build/
        cp -r sd build/
        cp -r fonts build/
        cp *.json *.md build/
        cp code.py boot.py build/

    - name: Upload build artifact
      uses: actions/upload-artifact@v4
      with:
        name: build-zip
        path: build