# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-python

name: Python application

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

permissions:
  contents: read

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Set up Python 3.10
      uses: actions/setup-python@v3
      with:
        python-version: "3.10"
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install flake8 pytest
        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
    - name: Lint with flake8
      run: |
        # stop the build if there are Python syntax errors or undefined names
        flake8 . --count --select=E9,F63,F7,F82 --show-source --statistics
        # exit-zero treats all errors as warnings. The GitHub editor is 127 chars wide
        flake8 . --count --exit-zero --max-complexity=10 --max-line-length=127 --statistics
    #- name: Test with pytest
    #  run: |
    #    pytest
    - name: actions_python_mypy
      # You may pin to the exact commit or the version.
      # uses: davidslusser/actions_python_mypy@73a0111379dc6b098e58b83445899f252e92ab6c
      uses: davidslusser/actions_python_mypy@v1.0.1
      #with:
        # additional parameters to be passed to the mypy command
        #options: # optional, default is 
          # command used to install python dependancies
        #pip_install_command: # optional, default is pip install mypy
          # version of python to run action with
        #python_version: # optional, default is 3.x
          # 
        #src: # optional, default is .
